create database if not exists JAVA_MYSQL;

use JAVA_MYSQL;

CREATE TABLE `LOG_ENTRY` (
  `ID` int(11) NOT NULL,
  `ACCESS_DATE_TIME` datetime DEFAULT NULL,
  `IP_ADDRESS` varchar(255) DEFAULT NULL,
  `CLIENT_IDENTIFIER` varchar(255) DEFAULT NULL,
  `HTTP_METHOD` varchar(255) DEFAULT NULL,
  `HTTP_STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `BLOCKED_ADDRESS_COMMENT` (
  `ID` int(11) NOT NULL,
  `IP_ADDRESS` varchar(255) DEFAULT NULL,
  `COMMENT` varchar(255) DEFAULT NULL,
  `HTTP_STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
